### ISSUE TITLE
Bulk open send button showing always disable.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Maana-Creation-StoreRedes--29-April-22#21]
Bug - Bulk open send button showing always disable.
Exp - send button should get enable after filling form.
Ref Link - https://nimb.ws/8EpRgT

**Comment by devAbhishekYadav** [comment]
https://www.awesomescreenshot.com/video/9063178?key=a068549850c35cf7c3156690d2946ad2
pls check its working fine

**Comment by ankitcedcoss** [comment]
Bug Fixed
